/*
  utils/errors.js
  Error Codes for custom error types
*/
const INVALID_DATA_ERROR = 400;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const DATA_CONFLICT_ERROR = 409;
const AUTH_REVOKED_ERROR = 410;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  INVALID_DATA_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  DATA_CONFLICT_ERROR,
  AUTH_REVOKED_ERROR,
  INTERNAL_SERVER_ERROR,
};
